"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from "react"

export type Language = "en" | "ru" | "uz"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.contests": "Contests",
    "nav.dashboard": "Dashboard",
    "nav.judge": "Judge",
    "nav.results": "Results",
    "nav.admin": "Admin",
    "nav.signIn": "Sign In",
    "nav.getStarted": "Get Started",
    
    // Home page
    "home.hero.title": "Master Competitive Programming",
    "home.hero.subtitle": "Join thousands of students improving their coding skills through contests, challenges, and real-time feedback.",
    "home.hero.cta": "Start Competing",
    "home.hero.secondary": "Browse Contests",
    "home.features.title": "Why Choose Evalix?",
    "home.features.subtitle": "Everything you need to excel in competitive programming",
    "home.feature1.title": "Real-time Judging",
    "home.feature1.desc": "Get instant feedback on your submissions with our lightning-fast evaluation system.",
    "home.feature2.title": "Diverse Problems",
    "home.feature2.desc": "From beginner to advanced, tackle problems across algorithms, data structures, and more.",
    "home.feature3.title": "Global Leaderboard",
    "home.feature3.desc": "Compete with programmers worldwide and track your progress on our ranking system.",
    "home.feature4.title": "Learn & Grow",
    "home.feature4.desc": "Access detailed solutions and editorial content to improve your problem-solving skills.",
    "home.stats.users": "Active Users",
    "home.stats.problems": "Problems",
    "home.stats.submissions": "Submissions",
    "home.stats.contests": "Contests",
    "home.cta.title": "Ready to Start Your Journey?",
    "home.cta.subtitle": "Join Evalix today and become a better programmer",
    "home.cta.button": "Create Free Account",
    
    // Auth
    "auth.login.title": "Welcome Back",
    "auth.login.subtitle": "Sign in to continue your journey",
    "auth.login.email": "Email",
    "auth.login.password": "Password",
    "auth.login.remember": "Remember me",
    "auth.login.forgot": "Forgot password?",
    "auth.login.submit": "Sign In",
    "auth.login.noAccount": "Don't have an account?",
    "auth.login.register": "Register",
    "auth.login.or": "Or continue with",
    "auth.register.title": "Create Account",
    "auth.register.subtitle": "Start your competitive programming journey",
    "auth.register.username": "Username",
    "auth.register.email": "Email",
    "auth.register.password": "Password",
    "auth.register.confirm": "Confirm Password",
    "auth.register.terms": "I agree to the Terms of Service and Privacy Policy",
    "auth.register.submit": "Create Account",
    "auth.register.hasAccount": "Already have an account?",
    "auth.register.login": "Sign In",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back",
    "dashboard.stats.solved": "Problems Solved",
    "dashboard.stats.submissions": "Submissions",
    "dashboard.stats.rating": "Rating",
    "dashboard.stats.rank": "Global Rank",
    "dashboard.recent.title": "Recent Submissions",
    "dashboard.recent.empty": "No submissions yet",
    "dashboard.recent.emptyDesc": "Start solving problems to see your submissions here",
    "dashboard.upcoming.title": "Upcoming Contests",
    "dashboard.upcoming.empty": "No upcoming contests",
    "dashboard.upcoming.emptyDesc": "Check back later for new contests",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.action.practice": "Practice Problems",
    "dashboard.action.contests": "Join Contest",
    "dashboard.action.leaderboard": "View Leaderboard",
    
    // Contests
    "contests.title": "Contests",
    "contests.subtitle": "Participate in competitive programming contests",
    "contests.tabs.upcoming": "Upcoming",
    "contests.tabs.ongoing": "Ongoing",
    "contests.tabs.past": "Past",
    "contests.empty": "No contests available",
    "contests.emptyDesc": "Check back later for new contests",
    "contests.register": "Register",
    "contests.enter": "Enter Contest",
    "contests.view": "View Results",
    "contests.participants": "participants",
    "contests.problems": "problems",
    "contests.duration": "Duration",
    "contests.starts": "Starts",
    "contests.ended": "Ended",
    
    // Contest Detail
    "contest.overview": "Overview",
    "contest.problems": "Problems",
    "contest.submissions": "My Submissions",
    "contest.standings": "Standings",
    "contest.rules": "Rules",
    "contest.timeRemaining": "Time Remaining",
    "contest.submitSolution": "Submit Solution",
    "contest.problem.difficulty": "Difficulty",
    "contest.problem.points": "Points",
    "contest.problem.solved": "Solved",
    "contest.standings.rank": "Rank",
    "contest.standings.user": "User",
    "contest.standings.score": "Score",
    "contest.standings.penalty": "Penalty",
    "contest.standings.empty": "No standings yet",
    "contest.standings.emptyDesc": "Standings will appear when participants submit solutions",
    
    // Submission
    "submit.title": "Submit Solution",
    "submit.problem": "Problem",
    "submit.language": "Language",
    "submit.code": "Your Code",
    "submit.placeholder": "// Write your solution here...",
    "submit.button": "Submit",
    "submit.reset": "Reset",
    
    // Judge
    "judge.title": "Judge Panel",
    "judge.subtitle": "Review and evaluate submissions",
    "judge.filters": "Filters",
    "judge.status": "Status",
    "judge.status.all": "All",
    "judge.status.pending": "Pending",
    "judge.status.accepted": "Accepted",
    "judge.status.rejected": "Rejected",
    "judge.submissions": "Submissions",
    "judge.empty": "No submissions to review",
    "judge.emptyDesc": "Submissions will appear here when participants submit solutions",
    "judge.review": "Review",
    "judge.accept": "Accept",
    "judge.reject": "Reject",
    
    // Results
    "results.title": "Results & Leaderboard",
    "results.subtitle": "Global rankings and contest results",
    "results.tabs.global": "Global Ranking",
    "results.tabs.contests": "Contest Results",
    "results.tabs.ratings": "Rating Changes",
    "results.rank": "Rank",
    "results.user": "User",
    "results.rating": "Rating",
    "results.solved": "Solved",
    "results.empty": "No results yet",
    "results.emptyDesc": "Results will appear after contests are completed",
    
    // Admin
    "admin.title": "Admin Panel",
    "admin.subtitle": "Manage contests, problems, and users",
    "admin.tabs.contests": "Contests",
    "admin.tabs.problems": "Problems",
    "admin.tabs.users": "Users",
    "admin.tabs.settings": "Settings",
    "admin.create": "Create New",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.save": "Save Changes",
    "admin.cancel": "Cancel",
    "admin.contest.name": "Contest Name",
    "admin.contest.description": "Description",
    "admin.contest.startTime": "Start Time",
    "admin.contest.endTime": "End Time",
    "admin.problem.title": "Problem Title",
    "admin.problem.description": "Description",
    "admin.problem.difficulty": "Difficulty",
    "admin.problem.points": "Points",
    "admin.problem.testCases": "Test Cases",
    "admin.users.username": "Username",
    "admin.users.email": "Email",
    "admin.users.role": "Role",
    "admin.users.status": "Status",
    "admin.empty": "No items found",
    "admin.emptyDesc": "Create your first item to get started",
    
    // Footer
    "footer.about": "About",
    "footer.contact": "Contact",
    "footer.terms": "Terms",
    "footer.privacy": "Privacy",
    "footer.rights": "All rights reserved",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.retry": "Retry",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.noResults": "No results found",
    "common.viewAll": "View All",
  },
  ru: {
    // Navbar
    "nav.home": "Главная",
    "nav.contests": "Соревнования",
    "nav.dashboard": "Панель",
    "nav.judge": "Жюри",
    "nav.results": "Результаты",
    "nav.admin": "Админ",
    "nav.signIn": "Войти",
    "nav.getStarted": "Начать",
    
    // Home page
    "home.hero.title": "Освойте Спортивное Программирование",
    "home.hero.subtitle": "Присоединяйтесь к тысячам студентов, улучшающих навыки программирования через соревнования и мгновенную обратную связь.",
    "home.hero.cta": "Начать Соревноваться",
    "home.hero.secondary": "Смотреть Соревнования",
    "home.features.title": "Почему Evalix?",
    "home.features.subtitle": "Все необходимое для успеха в спортивном программировании",
    "home.feature1.title": "Мгновенная Проверка",
    "home.feature1.desc": "Получайте мгновенную обратную связь с нашей молниеносной системой оценки.",
    "home.feature2.title": "Разнообразные Задачи",
    "home.feature2.desc": "От начального до продвинутого уровня - алгоритмы, структуры данных и многое другое.",
    "home.feature3.title": "Мировой Рейтинг",
    "home.feature3.desc": "Соревнуйтесь с программистами со всего мира и отслеживайте свой прогресс.",
    "home.feature4.title": "Учись и Развивайся",
    "home.feature4.desc": "Доступ к подробным решениям для улучшения навыков решения задач.",
    "home.stats.users": "Активных Пользователей",
    "home.stats.problems": "Задач",
    "home.stats.submissions": "Решений",
    "home.stats.contests": "Соревнований",
    "home.cta.title": "Готовы Начать?",
    "home.cta.subtitle": "Присоединяйтесь к Evalix сегодня",
    "home.cta.button": "Создать Аккаунт",
    
    // Auth
    "auth.login.title": "С Возвращением",
    "auth.login.subtitle": "Войдите, чтобы продолжить",
    "auth.login.email": "Электронная почта",
    "auth.login.password": "Пароль",
    "auth.login.remember": "Запомнить меня",
    "auth.login.forgot": "Забыли пароль?",
    "auth.login.submit": "Войти",
    "auth.login.noAccount": "Нет аккаунта?",
    "auth.login.register": "Зарегистрироваться",
    "auth.login.or": "Или продолжить с",
    "auth.register.title": "Создать Аккаунт",
    "auth.register.subtitle": "Начните свой путь в программировании",
    "auth.register.username": "Имя пользователя",
    "auth.register.email": "Электронная почта",
    "auth.register.password": "Пароль",
    "auth.register.confirm": "Подтвердите Пароль",
    "auth.register.terms": "Я согласен с Условиями использования",
    "auth.register.submit": "Создать Аккаунт",
    "auth.register.hasAccount": "Уже есть аккаунт?",
    "auth.register.login": "Войти",
    
    // Dashboard
    "dashboard.title": "Панель Управления",
    "dashboard.welcome": "С возвращением",
    "dashboard.stats.solved": "Решено Задач",
    "dashboard.stats.submissions": "Отправлено",
    "dashboard.stats.rating": "Рейтинг",
    "dashboard.stats.rank": "Мировой Ранг",
    "dashboard.recent.title": "Последние Решения",
    "dashboard.recent.empty": "Пока нет решений",
    "dashboard.recent.emptyDesc": "Начните решать задачи",
    "dashboard.upcoming.title": "Предстоящие Соревнования",
    "dashboard.upcoming.empty": "Нет предстоящих соревнований",
    "dashboard.upcoming.emptyDesc": "Проверьте позже",
    "dashboard.quickActions": "Быстрые Действия",
    "dashboard.action.practice": "Практика",
    "dashboard.action.contests": "Соревнования",
    "dashboard.action.leaderboard": "Рейтинг",
    
    // Contests
    "contests.title": "Соревнования",
    "contests.subtitle": "Участвуйте в соревнованиях по программированию",
    "contests.tabs.upcoming": "Предстоящие",
    "contests.tabs.ongoing": "Текущие",
    "contests.tabs.past": "Прошедшие",
    "contests.empty": "Нет доступных соревнований",
    "contests.emptyDesc": "Проверьте позже",
    "contests.register": "Регистрация",
    "contests.enter": "Войти",
    "contests.view": "Результаты",
    "contests.participants": "участников",
    "contests.problems": "задач",
    "contests.duration": "Длительность",
    "contests.starts": "Начало",
    "contests.ended": "Завершено",
    
    // Contest Detail
    "contest.overview": "Обзор",
    "contest.problems": "Задачи",
    "contest.submissions": "Мои Решения",
    "contest.standings": "Таблица",
    "contest.rules": "Правила",
    "contest.timeRemaining": "Осталось Времени",
    "contest.submitSolution": "Отправить Решение",
    "contest.problem.difficulty": "Сложность",
    "contest.problem.points": "Баллы",
    "contest.problem.solved": "Решено",
    "contest.standings.rank": "Место",
    "contest.standings.user": "Пользователь",
    "contest.standings.score": "Баллы",
    "contest.standings.penalty": "Штраф",
    "contest.standings.empty": "Пока нет результатов",
    "contest.standings.emptyDesc": "Результаты появятся после отправки решений",
    
    // Submission
    "submit.title": "Отправить Решение",
    "submit.problem": "Задача",
    "submit.language": "Язык",
    "submit.code": "Ваш Код",
    "submit.placeholder": "// Напишите ваше решение здесь...",
    "submit.button": "Отправить",
    "submit.reset": "Сбросить",
    
    // Judge
    "judge.title": "Панель Жюри",
    "judge.subtitle": "Проверка и оценка решений",
    "judge.filters": "Фильтры",
    "judge.status": "Статус",
    "judge.status.all": "Все",
    "judge.status.pending": "Ожидают",
    "judge.status.accepted": "Принятые",
    "judge.status.rejected": "Отклоненные",
    "judge.submissions": "Решения",
    "judge.empty": "Нет решений для проверки",
    "judge.emptyDesc": "Решения появятся здесь",
    "judge.review": "Проверить",
    "judge.accept": "Принять",
    "judge.reject": "Отклонить",
    
    // Results
    "results.title": "Результаты и Рейтинг",
    "results.subtitle": "Мировой рейтинг и результаты соревнований",
    "results.tabs.global": "Мировой Рейтинг",
    "results.tabs.contests": "Результаты",
    "results.tabs.ratings": "Изменения Рейтинга",
    "results.rank": "Место",
    "results.user": "Пользователь",
    "results.rating": "Рейтинг",
    "results.solved": "Решено",
    "results.empty": "Пока нет результатов",
    "results.emptyDesc": "Результаты появятся после завершения соревнований",
    
    // Admin
    "admin.title": "Панель Администратора",
    "admin.subtitle": "Управление соревнованиями, задачами и пользователями",
    "admin.tabs.contests": "Соревнования",
    "admin.tabs.problems": "Задачи",
    "admin.tabs.users": "Пользователи",
    "admin.tabs.settings": "Настройки",
    "admin.create": "Создать",
    "admin.edit": "Редактировать",
    "admin.delete": "Удалить",
    "admin.save": "Сохранить",
    "admin.cancel": "Отмена",
    "admin.contest.name": "Название",
    "admin.contest.description": "Описание",
    "admin.contest.startTime": "Начало",
    "admin.contest.endTime": "Окончание",
    "admin.problem.title": "Название Задачи",
    "admin.problem.description": "Описание",
    "admin.problem.difficulty": "Сложность",
    "admin.problem.points": "Баллы",
    "admin.problem.testCases": "Тесты",
    "admin.users.username": "Имя Пользователя",
    "admin.users.email": "Почта",
    "admin.users.role": "Роль",
    "admin.users.status": "Статус",
    "admin.empty": "Ничего не найдено",
    "admin.emptyDesc": "Создайте первый элемент",
    
    // Footer
    "footer.about": "О нас",
    "footer.contact": "Контакты",
    "footer.terms": "Условия",
    "footer.privacy": "Конфиденциальность",
    "footer.rights": "Все права защищены",
    
    // Common
    "common.loading": "Загрузка...",
    "common.error": "Произошла ошибка",
    "common.retry": "Повторить",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.previous": "Назад",
    "common.search": "Поиск",
    "common.filter": "Фильтр",
    "common.sort": "Сортировка",
    "common.noResults": "Ничего не найдено",
    "common.viewAll": "Смотреть Все",
  },
  uz: {
    // Navbar
    "nav.home": "Bosh Sahifa",
    "nav.contests": "Musobaqalar",
    "nav.dashboard": "Panel",
    "nav.judge": "Hakam",
    "nav.results": "Natijalar",
    "nav.admin": "Admin",
    "nav.signIn": "Kirish",
    "nav.getStarted": "Boshlash",
    
    // Home page
    "home.hero.title": "Raqobatbardosh Dasturlashni O'rganing",
    "home.hero.subtitle": "Musobaqalar va tezkor natijalar orqali dasturlash ko'nikmalarini oshirayotgan minglab talabalarga qo'shiling.",
    "home.hero.cta": "Musobaqani Boshlash",
    "home.hero.secondary": "Musobaqalarni Ko'rish",
    "home.features.title": "Nima Uchun Evalix?",
    "home.features.subtitle": "Raqobatbardosh dasturlashda muvaffaqiyat uchun kerak bo'lgan hamma narsa",
    "home.feature1.title": "Tezkor Tekshirish",
    "home.feature1.desc": "Bizning tez baholash tizimimiz bilan darhol natija oling.",
    "home.feature2.title": "Turli Masalalar",
    "home.feature2.desc": "Boshlang'ich darajadan murakkabgacha - algoritmlar, ma'lumotlar tuzilmalari va boshqalar.",
    "home.feature3.title": "Jahon Reytingi",
    "home.feature3.desc": "Butun dunyo dasturchilari bilan raqobatlashing va o'z taraqqiyotingizni kuzating.",
    "home.feature4.title": "O'rganing va Rivojlaning",
    "home.feature4.desc": "Muammolarni hal qilish ko'nikmalarini yaxshilash uchun batafsil yechimlardan foydalaning.",
    "home.stats.users": "Faol Foydalanuvchilar",
    "home.stats.problems": "Masalalar",
    "home.stats.submissions": "Yechimlar",
    "home.stats.contests": "Musobaqalar",
    "home.cta.title": "Boshlashga Tayyormisiz?",
    "home.cta.subtitle": "Bugun Evalix'ga qo'shiling",
    "home.cta.button": "Bepul Hisob Yarating",
    
    // Auth
    "auth.login.title": "Xush Kelibsiz",
    "auth.login.subtitle": "Davom etish uchun tizimga kiring",
    "auth.login.email": "Elektron pochta",
    "auth.login.password": "Parol",
    "auth.login.remember": "Eslab qolish",
    "auth.login.forgot": "Parolni unutdingizmi?",
    "auth.login.submit": "Kirish",
    "auth.login.noAccount": "Hisobingiz yo'qmi?",
    "auth.login.register": "Ro'yxatdan o'tish",
    "auth.login.or": "Yoki davom eting",
    "auth.register.title": "Hisob Yaratish",
    "auth.register.subtitle": "Dasturlash sayohatingizni boshlang",
    "auth.register.username": "Foydalanuvchi nomi",
    "auth.register.email": "Elektron pochta",
    "auth.register.password": "Parol",
    "auth.register.confirm": "Parolni Tasdiqlang",
    "auth.register.terms": "Foydalanish shartlariga roziman",
    "auth.register.submit": "Hisob Yaratish",
    "auth.register.hasAccount": "Hisobingiz bormi?",
    "auth.register.login": "Kirish",
    
    // Dashboard
    "dashboard.title": "Boshqaruv Paneli",
    "dashboard.welcome": "Xush kelibsiz",
    "dashboard.stats.solved": "Yechilgan Masalalar",
    "dashboard.stats.submissions": "Yuborilgan",
    "dashboard.stats.rating": "Reyting",
    "dashboard.stats.rank": "Jahon Darajasi",
    "dashboard.recent.title": "So'nggi Yechimlar",
    "dashboard.recent.empty": "Hali yechimlar yo'q",
    "dashboard.recent.emptyDesc": "Masalalarni yechishni boshlang",
    "dashboard.upcoming.title": "Kelgusi Musobaqalar",
    "dashboard.upcoming.empty": "Kelgusi musobaqalar yo'q",
    "dashboard.upcoming.emptyDesc": "Keyinroq tekshiring",
    "dashboard.quickActions": "Tezkor Harakatlar",
    "dashboard.action.practice": "Mashq",
    "dashboard.action.contests": "Musobaqalar",
    "dashboard.action.leaderboard": "Reyting",
    
    // Contests
    "contests.title": "Musobaqalar",
    "contests.subtitle": "Dasturlash musobaqalarida qatnashing",
    "contests.tabs.upcoming": "Kelgusi",
    "contests.tabs.ongoing": "Joriy",
    "contests.tabs.past": "O'tgan",
    "contests.empty": "Musobaqalar mavjud emas",
    "contests.emptyDesc": "Keyinroq tekshiring",
    "contests.register": "Ro'yxatdan o'tish",
    "contests.enter": "Kirish",
    "contests.view": "Natijalar",
    "contests.participants": "ishtirokchi",
    "contests.problems": "masala",
    "contests.duration": "Davomiyligi",
    "contests.starts": "Boshlanishi",
    "contests.ended": "Tugadi",
    
    // Contest Detail
    "contest.overview": "Ko'rib chiqish",
    "contest.problems": "Masalalar",
    "contest.submissions": "Mening Yechimlarim",
    "contest.standings": "Jadval",
    "contest.rules": "Qoidalar",
    "contest.timeRemaining": "Qolgan Vaqt",
    "contest.submitSolution": "Yechim Yuborish",
    "contest.problem.difficulty": "Qiyinlik",
    "contest.problem.points": "Ball",
    "contest.problem.solved": "Yechilgan",
    "contest.standings.rank": "O'rin",
    "contest.standings.user": "Foydalanuvchi",
    "contest.standings.score": "Ball",
    "contest.standings.penalty": "Jarima",
    "contest.standings.empty": "Hali natijalar yo'q",
    "contest.standings.emptyDesc": "Yechimlar yuborilganda natijalar paydo bo'ladi",
    
    // Submission
    "submit.title": "Yechim Yuborish",
    "submit.problem": "Masala",
    "submit.language": "Til",
    "submit.code": "Sizning Kodingiz",
    "submit.placeholder": "// Yechimingizni shu yerda yozing...",
    "submit.button": "Yuborish",
    "submit.reset": "Tozalash",
    
    // Judge
    "judge.title": "Hakamlar Paneli",
    "judge.subtitle": "Yechimlarni ko'rib chiqish va baholash",
    "judge.filters": "Filtrlar",
    "judge.status": "Holat",
    "judge.status.all": "Barchasi",
    "judge.status.pending": "Kutilmoqda",
    "judge.status.accepted": "Qabul qilingan",
    "judge.status.rejected": "Rad etilgan",
    "judge.submissions": "Yechimlar",
    "judge.empty": "Ko'rib chiqish uchun yechimlar yo'q",
    "judge.emptyDesc": "Yechimlar bu yerda paydo bo'ladi",
    "judge.review": "Ko'rib chiqish",
    "judge.accept": "Qabul qilish",
    "judge.reject": "Rad etish",
    
    // Results
    "results.title": "Natijalar va Reyting",
    "results.subtitle": "Jahon reytingi va musobaqa natijalari",
    "results.tabs.global": "Jahon Reytingi",
    "results.tabs.contests": "Natijalar",
    "results.tabs.ratings": "Reyting O'zgarishlari",
    "results.rank": "O'rin",
    "results.user": "Foydalanuvchi",
    "results.rating": "Reyting",
    "results.solved": "Yechilgan",
    "results.empty": "Hali natijalar yo'q",
    "results.emptyDesc": "Musobaqalar tugagandan keyin natijalar paydo bo'ladi",
    
    // Admin
    "admin.title": "Admin Paneli",
    "admin.subtitle": "Musobaqalar, masalalar va foydalanuvchilarni boshqarish",
    "admin.tabs.contests": "Musobaqalar",
    "admin.tabs.problems": "Masalalar",
    "admin.tabs.users": "Foydalanuvchilar",
    "admin.tabs.settings": "Sozlamalar",
    "admin.create": "Yaratish",
    "admin.edit": "Tahrirlash",
    "admin.delete": "O'chirish",
    "admin.save": "Saqlash",
    "admin.cancel": "Bekor qilish",
    "admin.contest.name": "Nomi",
    "admin.contest.description": "Tavsif",
    "admin.contest.startTime": "Boshlanish vaqti",
    "admin.contest.endTime": "Tugash vaqti",
    "admin.problem.title": "Masala nomi",
    "admin.problem.description": "Tavsif",
    "admin.problem.difficulty": "Qiyinlik",
    "admin.problem.points": "Ball",
    "admin.problem.testCases": "Test holatlari",
    "admin.users.username": "Foydalanuvchi nomi",
    "admin.users.email": "Elektron pochta",
    "admin.users.role": "Rol",
    "admin.users.status": "Holat",
    "admin.empty": "Hech narsa topilmadi",
    "admin.emptyDesc": "Birinchi elementni yarating",
    
    // Footer
    "footer.about": "Biz haqimizda",
    "footer.contact": "Aloqa",
    "footer.terms": "Shartlar",
    "footer.privacy": "Maxfiylik",
    "footer.rights": "Barcha huquqlar himoyalangan",
    
    // Common
    "common.loading": "Yuklanmoqda...",
    "common.error": "Xatolik yuz berdi",
    "common.retry": "Qayta urinish",
    "common.back": "Orqaga",
    "common.next": "Keyingi",
    "common.previous": "Oldingi",
    "common.search": "Qidirish",
    "common.filter": "Filtr",
    "common.sort": "Saralash",
    "common.noResults": "Hech narsa topilmadi",
    "common.viewAll": "Barchasini Ko'rish",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  useEffect(() => {
    const saved = localStorage.getItem("evalix-language") as Language
    if (saved && (saved === "en" || saved === "ru" || saved === "uz")) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("evalix-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
